"use client";

/** Renders a raw assistant message string, handling:
 *  - __IMG__url__IMG__  → <img> element
 *  - {"tool":"..."}      → styled tool card
 *  - everything else     → plain text
 */

function ToolCard({ raw }: { raw: string }) {
  try {
    const obj = JSON.parse(raw);
    const tool: string = obj.tool;

    const colors: Record<string, string> = {
      email:     "border-blue-500/30 bg-blue-500/5 text-blue-300",
      calendar:  "border-emerald-500/30 bg-emerald-500/5 text-emerald-300",
      crm:       "border-amber-500/30 bg-amber-500/5 text-amber-300",
      image_gen: "border-violet-500/30 bg-violet-500/5 text-violet-300",
      qr:        "border-teal-500/30 bg-teal-500/5 text-teal-300",
      translate: "border-cyan-500/30 bg-cyan-500/5 text-cyan-300",
    };
    const labels: Record<string, string> = {
      email:     "📧 Email",
      calendar:  "📅 Calendar",
      crm:       "🏢 CRM",
      image_gen: "🎨 Image Generation",
      qr:        "⬛ QR Code",
      translate: "🌐 Translation",
    };

    const cls = colors[tool] ?? "border-white/10 bg-white/5 text-white/70";
    const label = labels[tool] ?? tool;

    return (
      <div className={`mt-2 rounded-xl border px-3 py-2.5 text-xs ${cls}`}>
        <div className="font-semibold mb-1">{label}</div>
        {Object.entries(obj)
          .filter(([k]) => k !== "tool")
          .map(([k, v]) => (
            <div key={k} className="flex gap-2">
              <span className="opacity-60 capitalize">{k}:</span>
              <span className="break-all">{String(v)}</span>
            </div>
          ))}
      </div>
    );
  } catch {
    return null;
  }
}

// Splits a string on __IMG__url__IMG__ and {"tool":...} blocks,
// returning an array of typed segments.
type Segment =
  | { kind: "text"; value: string }
  | { kind: "image"; url: string }
  | { kind: "tool"; json: string };

function parseSegments(raw: string): Segment[] {
  const segments: Segment[] = [];

  // Pattern: __IMG__....__IMG__ OR {"tool":"..."}
  const pattern = /__IMG__([\s\S]+?)__IMG__|(\{"tool":"[\s\S]+?"\}[^}]*\}|\{"tool":"[^"]+"\})/g;

  let last = 0;
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(raw)) !== null) {
    if (match.index > last) {
      segments.push({ kind: "text", value: raw.slice(last, match.index) });
    }
    if (match[1] !== undefined) {
      // __IMG__ tag
      segments.push({ kind: "image", url: match[1] });
    } else if (match[2] !== undefined) {
      // tool JSON card
      segments.push({ kind: "tool", json: match[2] });
    }
    last = match.index + match[0].length;
  }

  if (last < raw.length) {
    segments.push({ kind: "text", value: raw.slice(last) });
  }

  return segments;
}

export function MessageRenderer({ content }: { content: string }) {
  const segments = parseSegments(content);

  return (
    <div>
      {segments.map((seg, i) => {
        if (seg.kind === "image") {
          return (
            <img
              key={i}
              src={seg.url}
              alt="Generated by Lyra"
              className="mt-3 rounded-xl max-w-full border border-white/10"
            />
          );
        }
        if (seg.kind === "tool") {
          return <ToolCard key={i} raw={seg.json} />;
        }
        if (seg.value.trim()) {
          return (
            <p key={i} className="whitespace-pre-wrap">
              {seg.value}
            </p>
          );
        }
        return null;
      })}
    </div>
  );
}
