"use client";

/** Renders a raw assistant message string, handling:
 *  - __IMG__url__IMG__  → <img> element
 *  - {"tool":"..."}      → styled tool card
 *  - everything else     → plain text
 */

function ToolCard({ raw }: { raw: string }) {
  try {
    const obj = JSON.parse(raw);
    const tool: string = obj.tool;

    const colors: Record<string, string> = {
      email:     "border-blue-500/30 bg-blue-500/5 text-blue-300",
      calendar:  "border-emerald-500/30 bg-emerald-500/5 text-emerald-300",
      crm:       "border-amber-500/30 bg-amber-500/5 text-amber-300",
      image_gen: "border-violet-500/30 bg-violet-500/5 text-violet-300",
      qr:        "border-teal-500/30 bg-teal-500/5 text-teal-300",
      translate: "border-cyan-500/30 bg-cyan-500/5 text-cyan-300",
    };
    const labels: Record<string, string> = {
      email:     "📧 Email",
      calendar:  "📅 Calendar",
      crm:       "🏢 CRM",
      image_gen: "🎨 Image Generation",
      qr:        "⬛ QR Code",
      translate: "🌐 Translation",
    };

    const cls = colors[tool] ?? "border-white/10 bg-white/5 text-white/70";
    const label = labels[tool] ?? tool;

    return (
      <div className={`mt-2 rounded-xl border px-3 py-2.5 text-xs ${cls}`}>
        <div className="font-semibold mb-1">{label}</div>
        {Object.entries(obj)
          .filter(([k]) => k !== "tool")
          .map(([k, v]) => (
            <div key={k} className="flex gap-2">
              <span className="opacity-60 capitalize">{k}:</span>
              <span className="break-all">{String(v)}</span>
            </div>
          ))}
      </div>
    );
  } catch {
    return null;
  }
}

type Segment =
  | { kind: "text"; value: string }
  | { kind: "image"; url: string }
  | { kind: "tool"; json: string };

/** Character-level scanner — handles multi-field tool JSON correctly. */
function parseSegments(raw: string): Segment[] {
  const segments: Segment[] = [];
  const DELIM = "__IMG__";
  let i = 0;
  let textStart = 0;

  while (i < raw.length) {
    // ── __IMG__ image tag ────────────────────────────────────────
    if (raw.startsWith(DELIM, i)) {
      if (i > textStart) segments.push({ kind: "text", value: raw.slice(textStart, i) });
      const contentStart = i + DELIM.length;
      const closeIdx = raw.indexOf(DELIM, contentStart);
      if (closeIdx === -1) {
        // Incomplete tag mid-stream — treat rest as text
        textStart = i;
        break;
      }
      segments.push({ kind: "image", url: raw.slice(contentStart, closeIdx) });
      i = closeIdx + DELIM.length;
      textStart = i;
      continue;
    }

    // ── {"tool":...} JSON card ────────────────────────────────────
    if (raw.startsWith('{"tool":', i)) {
      if (i > textStart) segments.push({ kind: "text", value: raw.slice(textStart, i) });

      // Walk forward counting braces to find the matching `}`
      let depth = 0;
      let inString = false;
      let escaped = false;
      let end = -1;

      for (let j = i; j < raw.length; j++) {
        const c = raw[j];
        if (escaped) { escaped = false; continue; }
        if (c === "\\" && inString) { escaped = true; continue; }
        if (c === '"') { inString = !inString; continue; }
        if (!inString) {
          if (c === "{") depth++;
          else if (c === "}") { depth--; if (depth === 0) { end = j; break; } }
        }
      }

      if (end !== -1) {
        segments.push({ kind: "tool", json: raw.slice(i, end + 1) });
        i = end + 1;
        textStart = i;
      } else {
        // Incomplete JSON mid-stream — treat as text
        textStart = i;
        break;
      }
      continue;
    }

    i++;
  }

  // Flush remaining text
  if (textStart < raw.length) {
    segments.push({ kind: "text", value: raw.slice(textStart) });
  }

  return segments;
}

export function MessageRenderer({ content }: { content: string }) {
  const segments = parseSegments(content);

  return (
    <div>
      {segments.map((seg, i) => {
        if (seg.kind === "image") {
          return (
            <img
              key={i}
              src={seg.url}
              alt="Generated by Lyra"
              className="mt-3 rounded-xl max-w-full border border-white/10"
            />
          );
        }
        if (seg.kind === "tool") {
          return <ToolCard key={i} raw={seg.json} />;
        }
        if (seg.value.trim()) {
          return (
            <p key={i} className="whitespace-pre-wrap">
              {seg.value}
            </p>
          );
        }
        return null;
      })}
    </div>
  );
}
