import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Sparkles } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using AITaskFlo and Lyra.",
};

export default function TermsPage() {
  const updated = "April 4, 2026";
  return (
    <div className="min-h-screen text-white" style={{ background: "#080810" }}>
      <nav className="fixed top-0 w-full z-50 backdrop-blur-xl" style={{ background: "rgba(8,8,16,0.85)", borderBottom: "1px solid rgba(255,255,255,0.05)" }}>
        <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-violet-500 to-fuchsia-500 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <span className="text-lg font-bold text-white">AITaskFlo</span>
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 pt-28 pb-24">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-white/40 hover:text-white/70 transition-colors mb-10">
          <ArrowLeft className="w-4 h-4" /> Back
        </Link>

        <h1 className="text-4xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-white/35 text-sm mb-12">Last updated: {updated}</p>

        <div className="space-y-8" style={{ color: "rgba(255,255,255,0.55)" }}>
          {[
            {
              title: "1. Acceptance of Terms",
              body: `By creating an account or using AITaskFlo ("the Service"), you agree to these Terms. If you do not agree, do not use the Service.`,
            },
            {
              title: "2. Description of Service",
              body: `AITaskFlo provides access to Lyra, an AI assistant with persistent memory, reflection, and agent evolution capabilities. The Service is available via subscription plans as described on our pricing page.`,
            },
            {
              title: "3. Accounts",
              body: `You must provide accurate information when registering. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. Notify us immediately of unauthorized use at aitaskflo@gmail.com.`,
            },
            {
              title: "4. Acceptable Use",
              body: `You agree not to use the Service to: generate illegal content; harass, threaten, or harm others; attempt to circumvent rate limits or security measures; resell or redistribute the Service without authorization; or violate any applicable laws or regulations.`,
            },
            {
              title: "5. Subscriptions and Billing",
              body: `Paid plans are billed monthly. You authorize us to charge your payment method via Stripe. Cancellations take effect at the end of the current billing period. We do not offer refunds for partial months. Prices may change with 30 days notice.`,
            },
            {
              title: "6. Free Plan Limits",
              body: `Free accounts are subject to daily message limits as described on the pricing page. We reserve the right to modify free plan limits at any time.`,
            },
            {
              title: "7. Intellectual Property",
              body: `You retain ownership of content you provide. You grant us a limited license to process your content to deliver the Service. The Service itself — including its codebase, models, UI, and branding — is owned by AITaskFlo.`,
            },
            {
              title: "8. AI Output Disclaimer",
              body: `Lyra's responses are generated by AI and may be inaccurate or incomplete. Do not rely on AI output for medical, legal, financial, or safety-critical decisions. We make no warranty regarding the accuracy of AI-generated content.`,
            },
            {
              title: "8a. Clinical Features — Not a Medical Device",
              body: `The clinical assistant features of AITaskFlo (including EHR record tools, PubMed research, and SOAP note generation) are productivity and research tools only. They are NOT FDA-approved medical devices, NOT a substitute for professional medical judgment, and NOT intended for use in emergency or life-threatening situations. AI-generated clinical content must be independently reviewed by a licensed healthcare professional before any clinical action is taken.`,
            },
            {
              title: "8b. HIPAA and Protected Health Information",
              body: `If you are a Covered Entity or Business Associate as defined by HIPAA (45 CFR Parts 160 and 164), you must execute a Business Associate Agreement (BAA) with AITaskFlo before entering any Protected Health Information (PHI) into the Service. Do not enter real patient PHI without a signed BAA in place. AITaskFlo implements HIPAA technical safeguards including AES-256-GCM encryption at rest, full audit logging, and access controls. Our HIPAA Notice of Privacy Practices is available at /hipaa. To request a BAA, visit /baa or email aitaskflo@gmail.com.`,
            },
            {
              title: "9. Limitation of Liability",
              body: `To the maximum extent permitted by law, AITaskFlo is not liable for indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the past 12 months.`,
            },
            {
              title: "10. Termination",
              body: `We may suspend or terminate accounts that violate these Terms. You may close your account at any time. Upon termination, your right to use the Service ceases immediately.`,
            },
            {
              title: "11. Changes to Terms",
              body: `We may update these Terms. We will notify you of material changes via email or in-app notice. Continued use constitutes acceptance.`,
            },
            {
              title: "12. Governing Law",
              body: `These Terms are governed by the laws of the State of Illinois, United States. Disputes shall be resolved in the courts of Cook County, Illinois.`,
            },
            {
              title: "13. Contact",
              body: `Questions about these Terms? Email aitaskflo@gmail.com.`,
            },
            {
              title: "14. HIPAA Compliance",
              body: `AITaskFlo maintains HIPAA technical and administrative safeguards for the protection of PHI as required by 45 CFR Parts 160 and 164. Our Security and Privacy Officer can be reached at aitaskflo@gmail.com. Breach notifications will be provided within 60 calendar days of discovery in accordance with 45 CFR § 164.410. A full Business Associate Agreement is available at aitaskflo.com/baa.`,
            },
          ].map(({ title, body }) => (
            <section key={title}>
              <h2 className="text-white font-semibold text-base mb-2">{title}</h2>
              <p className="leading-relaxed">{body}</p>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
